version: 0.0.{build}
branches:
  only:
    - master
image:
  - Visual Studio 2019
  - Ubuntu1804
build_script:
- cmd: >-
    C:\Python37-x64\python.exe 3rdparty/download.py

    md build

    cd build

    cmake -G"Visual Studio 16 2019" -Ax64 -DBUILD_SHARED_LIBS=OFF ..

    cmake --build . --config Release --target ALL_BUILD
- sh: >-
    python3 ./3rdparty/download.py

    mkdir build
    
    cd build

    cmake -G"Unix Makefiles" -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Relase ..

    make -j2
test_script:
- cmd: >-
    cd C:\projects\libazul\build

    tests\async\Release\tests_azul_async.exe

    tests\compute\Release\tests_azul_compute.exe
    
    tests\ipc\Release\tests_azul_ipc.exe

    tests\utils\Release\tests_azul_utils.exe
- sh: >-
    cd /home/appveyor/projects/libazul/build/

    ./tests/async/tests_azul_async

    ./tests/compute/tests_azul_compute

    ./tests/ipc/tests_azul_ipc

    ./tests/utils/tests_azul_utils
