function (set_azul_platform_file)
    if ("${TARGET_PLATFORM}" STREQUAL "")
        set(TARGET_PLATFORM ${CMAKE_SYSTEM_NAME})
    endif()

    if (${TARGET_PLATFORM} MATCHES "Android")
        set(AZUL_PLATFORM_FILE "${CMAKE_SOURCE_DIR}/cmake/platforms/Android.cmake" PARENT_SCOPE)
    elseif (${TARGET_PLATFORM} MATCHES "Linux")
        set(AZUL_PLATFORM_FILE "${CMAKE_SOURCE_DIR}/cmake/platforms/Linux.cmake" PARENT_SCOPE)
    elseif (${TARGET_PLATFORM} MATCHES "Darwin")
        if (${IOS})
            set(AZUL_PLATFORM_FILE "${CMAKE_SOURCE_DIR}/cmake/platforms/iOS.cmake" PARENT_SCOPE)
        else()
            set(AZUL_PLATFORM_FILE "${CMAKE_SOURCE_DIR}/cmake/platforms/Darwin.cmake" PARENT_SCOPE)
        endif()
    elseif (${TARGET_PLATFORM} MATCHES "iOS")
        set(AZUL_PLATFORM_FILE "${CMAKE_SOURCE_DIR}/cmake/platforms/iOS.cmake" PARENT_SCOPE)
    elseif (${TARGET_PLATFORM} MATCHES "Windows")
        set(AZUL_PLATFORM_FILE "${CMAKE_SOURCE_DIR}/cmake/platforms/Windows.cmake" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Target (${TARGET_PLATFORM}) / Host (${CMAKE_SYSTEM_NAME}) combination atm not supported.")
    endif()
endfunction()
